import React from 'react';

export default function TopicThree() {
    return (
    <div>
        <h2>Statistical Process Control / Variation</h2>
        <p>Statistical process control and variation asked for us to analyze different situations and categorize them according to their details. We were asked to identify if measures should be classified as defects or defectives, and then whether hypothesized measures belonged to a group, were variables or attributes, and the most appropriate visualization tool to infer conclusions about the measures. This process allowed us to gain further insight into how statistical process control tools can be used in various settings. While all of the examples in the exercise were related to healthcare specifically, the nature of the problems are designed to easily apply to other industries as well. </p><br/>
        <p>Statistical process control measures gained importance and significance through its application to manufacturing process improvement, but they have since become more relevant in other industries as well. The examples provided in the assignment covered other metrics such as costs, counts of various items, and distances between units in medical facilities. Likewise, in other industries, these measures and variation analyses can make their way into business areas other than manufacturing. </p><br/>
        <p>Healthcare being such a vastly diverse industry has such a broad range of applications. Variability also has a very profound effect on healthcare when it comes to key areas such as cost, safety, efficiency, and patient outcomes. Given the complicated nature of healthcare, errors happen all the time, but statistical process control is key because it can help management infer whether issues are because of human error or systematic shortcomings. Monitoring things like infection rates, wait times, medication errors, and readmissions are all done consistently by facilities, and it is very important to quickly identify whether these are because of abnormal cases or if something in place is causing these outcomes. </p><br/>
        <p>The continuous nature of statistical process control is what makes it so powerful. With the increasing presence of technology and automation, it is now easier than ever to detect unexpected changes in these aforementioned areas. The focus on continuous improvement has never been this strong, and statistical process control ensures that these improvement efforts have a meaningful impact. While six sigma is implemented by those who are more statistically knowledgeable and advanced, statistical process controls can be monitored by a wider range of healthcare personnel. Even a nurse or doctor that has a very limited statistical background would be able to detect abnormalities given the measures are indicating such. The essence of statistical process control is to be able to detect these abnormalities in virtually any area possible, any subset of a healthcare facility that ouptuts key quantitative metrics. </p>
    </div>
    )
}