import React from 'react';

export default function TopicTwo() {
    return (
    <div>
        <h2>Six Sigma</h2>
        <p>Our assignment asked to research the cases of six sigma being properly implemented, as well as stories of successes generated within healthcare. We were provided with examples of success stories showing where six sigma has caused meaningful change. Subsequently, we covered various quantitative tools and methodologies that are used in six sigma, and in which component of the DMAIC process it appears. </p><br/>
        <p>Particular differences primarily included subsections of healthcare that six sigma can be applied to. Groups covering medical devices focused on how six sigma could enhance manufacturing and process improvement capabilities. Others highlighted similar deployments of six sigma in pharmaceutical manufacturing and addressing business cases. Within pharmaceuticals and medical devices, there was heightened focus on quality instead of efficiencies, with emphasis on adhering to various standards and guidelines. </p><br/>
        <p>In clinical and administrative processes, six sigma can be used in a variety of ways to reduce overall defectiveness and variability. Given the extensive nature as to what defectiveness can truly mean, such as medication errors, delays, infections, etc., six sigma can be applied in virtually any field to promote efficiency and reduce overall waste. Many patients even have fears of getting treated at medical facilities because they are worried about enduring long wait times; six sigma would be a useful tool to identify the steps that can be taken to mitigate these waiting times. </p><br/>
        <p>Six sigma is virtually all quantitative, so it takes into account curated data and applies methods to truly alleviate the source of inefficiencies. The DMAIC approach is very structured, so it provides a stronger and more concrete framework to follow to implement changes. Regarding the medical industry, it can be applied in as small or large of a scale as deemed necessary, giving it more versatility in overall problem solving. This nature also allows for it to be more widely used across departments in medical facilities and opens the door for cross-functional collaboration and interdisciplinary improvement. Although it presents these key strengths, six sigma does have limitations as well, mostly stemming from data availability, ambiguous problem sources, and adhering to rigorous processes. A problem would need to be identified with key quantitative issues, where as more behavioral and human-focused issues may not be best suited for six sigma. </p><br/>
        <p>My personal experience with six sigma has been applied in the manufacturing industry. While working for Nestle Health Science, the pilot plant engineers employed the methodology to increase flow times and produce higher quantities of product by identifying bottlenecks and causes of potential slowdown. It has also appeared in Lehigh’s curriculum in a more theoretical sense, by interpreting vast data and suggesting actions to take in order to improve these same issues. For healthcare, patient flow would be a strong suitor for six sigma, where as human-induced defects and behavioral issues may not be as clearly defined. </p>
    </div>
    )
}