import React from 'react';

export default function TopicOne() {
    return (
    <div>
        <h2>Human-Centered Design</h2>
        <p>The human-centered design assignment challenged us to research a process that could potentially be improved in our area of focus, communication and information technology. Our goal was to research how patient discharge and relevant follow-up considerations could be delivered in a more timely and accurate manner. The framework of this improvement was to engage with patients to understand the current struggles and shortcoming in this stage of patient flow. Our ideation method invited patients to submit feedback, with each subsequent iteration inviting the patients to provide a more interactive piece of feedback for hospital administrative staff to review. The purpose of this interactivity is to provide administrative staff with further visibility into patient feedback, allowing for further clarity in their improvement efforts. </p><br/>
        <p>Other efforts implemented the same theory of change and ideation method frameworks, but styled their approach in different ways. Whereas our group’s focus was to hone in on patient feedback through promoting clarity in the media they provided, others aimed to use the frameworks to further define their question at its source. Our question stayed similarly defined, but we used the frameworks provided to simplify our potential solutions. It was common for teams to frame the short-term challenges and simplify them into more tangible issues to solve. There were also many instances where groups attempted to frame the current problems that exist within their scope and define short-term solutions capable of accomplishing with simple changes. </p><br/>
        <p>Human-centered design is becoming increasingly important in healthcare, given the wider accessibility to technology and communication that has presented itself this century. Patients now more than ever can provide feedback and suggestions for how facilities can improve their overall experience. With that, the opportunities are virtually limitless, in conjunction with the improvement of technology and communication, facilities can deploy more of these measures than ever before. Examples such as patient portals, pre-operation modules, follow-up timelines, and more can give patients a more comprehensive understanding of their treatment. </p><br/>
        <p>The patient experience is critical for healthcare, patients exhibit common human behaviors such as trust, satisfaction, and comfort, all which can be enhanced with more of these measures in place. As a contrast to more quantitative measures, human-centered design inhibits the more qualitative side of healthcare, which is arguably more important overall. While quantitative measures can improve overall operational efficiency, enhancing the patient experience can improve retention rates and build stronger credibility and reliablity among the communities that healthcare facilities serve. </p><br/>
        <p>A particular advantage in improving patient-centered healthcare is that it does not require personnel to be as educated on topics specifically to drive change. Those who study psychology, sociology, human behavior, and similar subjects may actually be better suited to drive change in this area. With the increased presence of technology, even software developers and those with similar backgrounds could create lasting solutions. The patient experience could revolve around so many components of care that opportunities are so expansive to improve it. While its limitations lie in its timeliness and actual tangibility to the tools used to treat patients, ensuring the patient experience is as positive as possible could have a very lasting impact. </p><br/>
        <p>Coming from a family that works in healthcare, there has definitely been a noticeable shift away from operational focus to patient centeredness on an administrative level. The focus that administrators have is now more than ever centered around the patient specifically, and allowing patients to have a voice on their treatment has never been more paramount. Given that people from such a wide array of backgrounds can contribute to enhancing this, the opportunity for collaboration and interdisciplinary implementation is so vast. While some process improvement measures in healthcare are specifically concerned with very specific areas of focus, patient experience can be a key point for so many different departments, leaving it as one of the most important chances for overall improvement in the healthcare industry. </p>
    </div>
    )
}